command:
  - "/opt/keycloak/bin/kc.sh"
  - "start-dev"
  - "--http-port=8080"
  - "--hostname-strict=false"

extraEnv: |
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: admin
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    value: admin
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: admin
  - name: KC_HOSTNAME
    value: localhost
  - name: KC_HOSTNAME_PORT
    value: "8080"
  - name: JAVA_OPTS_APPEND
    value: -Djgroups.dns.query=keycloak-keycloakx-headless

http:
  httpEnabled: true

service:
  type: ClusterIP
