#!/usr/bin/env bash
# =============================================================================
#  05-install-keycloak.sh — the front office. Installs our Helm chart
#  (helm/keycloak) and imports the 'grocery' realm on first start.
#
#  The chart's settings are written to helm/keycloak/values-generated.yaml.
#  You can edit that file by hand (or with tools/set-config.sh --yaml) and
#  simply re-run this script to apply the change.
# =============================================================================
source "$(dirname "$0")/lib/common.sh"
require_cmd kubectl helm
need_generated BASE_DOMAIN

CHART="$ROOT_DIR/helm/keycloak"
VALUES="$CHART/values-generated.yaml"

step "1/5 Namespace '${NS_IDENTITY}'"
ensure_namespace "$NS_IDENTITY"

step "2/5 Writing ${VALUES}"
if [[ -f "$VALUES" && "${REGENERATE_VALUES:-false}" != "true" ]]; then
  log "values-generated.yaml already exists — keeping your edits (set REGENERATE_VALUES=true to rewrite it)"
else
cat > "$VALUES" <<EOT
# Generated by scripts/05-install-keycloak.sh from scripts/00-config.sh.
# Edit freely, then re-run scripts/05-install-keycloak.sh to apply.
image:
  tag: "${KC_IMAGE_TAG}"
hostname: "${KEYCLOAK_PUBLIC_URL}"
admin:
  username: "${KC_ADMIN_USER}"
  password: "${KC_ADMIN_PASSWORD}"
database:
  host: "${POSTGRES_HOST}"
  port: 5432
  name: keycloak
  username: keycloak
  password: "${KC_DB_PASSWORD}"
ingress:
  enabled: true
  className: nginx
  host: "keycloak.${BASE_DOMAIN}"
  tls:
    enabled: ${ENABLE_TLS}
    clusterIssuer: letsencrypt-prod
realm:
  import: true
  baseDomain: "${BASE_DOMAIN}"
  proto: "${PROTO}"
  sslRequired: "${SSL_REQUIRED}"
  demoPassword: "${DEMO_USER_PASSWORD}"
  javaClientSecret: "${JAVA_CLIENT_SECRET}"
  pythonClientSecret: "${PYTHON_CLIENT_SECRET}"
EOT
fi

step "3/5 helm lint + install/upgrade"
helm lint "$CHART" -f "$VALUES"
helm upgrade --install keycloak "$CHART" --namespace "$NS_IDENTITY" -f "$VALUES" --wait --timeout 15m

step "4/5 Waiting for Keycloak to answer"
wait_rollout "$NS_IDENTITY" deployment/keycloak 900s

if [[ "$PROTO" == "http" ]]; then
  step "5/5 Plain-http mode: allow the admin console over http (demo only!)"
  kcadm_login
  kcadm update realms/master -s sslRequired=NONE
  log "master realm sslRequired=NONE"
else
  step "5/5 TLS mode: nothing to relax"
fi

log "Done. Realm '${KC_REALM}' was imported from helm/keycloak/realms/grocery-realm.json"
print_urls
log "Next: scripts/06-configure-realm.sh (connects the LDAP phone book)"
