apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: apps
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: localhost:5001/demo-app:init
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: init
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
